baseURL = "https://poet-anindita.github.io/"
languageCode = "en"
title = "Poet Anindita"

[params]
  tagline = "Poems & Words"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Bengali Poems"
  identifier = "poems"
  url = "/poems/"
  weight = 2

[[menu.main]]
  name = "Aphorisms"
  identifier = "aphorisms"
  url = "/aphorisms/"
  weight = 3
